### ISSUE TITLE
certain laser read errors report as TimeoutError

### ISSUE THREAD

**Issue by echarlie** [furbrain/STIC#1]
sometimes when shooting at a reflective surface or at an odd angle surface, the screen displays `asyncio/funcs.py:75:wait_for TimeoutError:" rather than a Laser Read Error.

**Comment by furbrain** [comment]
Looks like the code that picks up on the last errors doesn't account for this. I'll need to fix this

**Comment by furbrain** [comment]
@echarlie  I'll make the timeout error give a nicer response.
Currently the timeout for the laser is set to 3s, would you prefer to wait longer and get a reading or get an error quicker?
