### ISSUE TITLE
Consider shortening tailcap by 5mm for better case fitment

### ISSUE THREAD

**Issue by echarlie** [furbrain/STIC#21]
The SAP6/STIC is approximately 5mm too long to fit nicely in a Peli 1030 micro case. As there aren't many options for cases *slightly* larger, and most people like to keep instruments in a case for transport (and to protect them from mud between stations), slightly modifying the dimensions for optimal fit in the Peli 1030 would be desirable.

![image](https://github.com/furbrain/STIC/assets/18043413/928cd4b7-4137-449a-b821-c2a06fac7eac)
![image](https://github.com/furbrain/STIC/assets/18043413/8b670301-e93b-4db9-b5a7-90e7669fcde6)

as you can see from the photos, it is a loose fit with the tailcap off, but a very close fit with the tailcap on (the case does in fact close, but the device is jammed in very tightly, with the tailcap wedged against the top foam). Shortening the tailcap (or the rest of the device) by 5-8mm would result in a very good fit.

**Comment by furbrain** [comment]
Thanks for the input. Next hardware version will be a bit shorter!

**Comment by furbrain** [comment]
The case in branch 6.2 now fits. Needs to be used with PCB from this branch![IMG_20240424_203415.jpg](https://github.com/furbrain/STIC/assets/2996189/14e7f2e7-130e-4eba-ad27-f265f9894163)

**Comment by furbrain** [comment]
Fixed in hardware version 6.2
